version: '3'
services:
  chart-tiler:
    build: .
    working_dir: /workspace/chart-tiler
    command: python -m charts_py
  web-client:
    image: node:18
    working_dir: /app
    volumes:
      - ./web-client:/app
    command: npm start
  nginx:
    image: nginx:alpine
    depends_on:
      - chart-tiler
    ports:
      - "8080:80"
    volumes:
      - ./static:/srv/static:ro
    command: |
      /bin/sh -c 'cat <<"EOF" >/etc/nginx/conf.d/default.conf
      server {
        location /map/ {
          proxy_pass http://chart-tiler:8000/;
          proxy_set_header Host $host;
          proxy_set_header X-Accel-Redirect $upstream_http_x_accel_redirect;
        }
        location /assets/ {
          internal;
          alias /srv/static/;
        }
      }
      EOF
      && nginx -g "daemon off;"'
