name: VDR CI

on:
  push:
    paths:
      - 'VDR/**'
      - 'Makefile'
      - '.github/workflows/vdr.yml'
  pull_request:
    paths:
      - 'VDR/**'
      - 'Makefile'
      - '.github/workflows/vdr.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r VDR/chart-tiler/requirements.txt pytest
      - name: Build styling artifacts
        run: make all
      - name: Run tests
        run: pytest VDR/chart-tiler/tests
