name: VDR CI

on:
  push:
    paths:
      - 'VDR/**'
      - 'Makefile'
      - '.github/workflows/vdr.yml'
  pull_request:
    paths:
      - 'VDR/**'
      - 'Makefile'
      - '.github/workflows/vdr.yml'

jobs:
  style-sprite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r VDR/chart-tiler/requirements.txt
      - name: Build styling artifacts
        run: make all
      - name: Upload styling artifacts
        uses: actions/upload-artifact@v3
        with:
          name: styling-dist
          path: VDR/server-styling/dist

  glyph-bake:
    runs-on: ubuntu-latest
    needs: style-sprite
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Download styling artifacts
        uses: actions/download-artifact@v3
        with:
          name: styling-dist
          path: VDR/server-styling/dist
      - name: Bake glyph PBFs
        run: |
          npm install -g @mapbox/fontnik
          mkdir -p VDR/server-styling/dist/glyphs
          fontnik VDR/BAUV/lib/tileserver-gl/public/resources/fonts/OpenSans-Regular.ttf \
            VDR/server-styling/dist/glyphs/OpenSans-Regular.pbf
      - name: Upload glyphs
        uses: actions/upload-artifact@v3
        with:
          name: glyphs
          path: VDR/server-styling/dist/glyphs

  tileserver-tests:
    runs-on: ubuntu-latest
    needs:
      - style-sprite
      - glyph-bake
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r VDR/chart-tiler/requirements.txt pytest
      - name: Retrieve styling artifacts
        uses: actions/download-artifact@v3
        with:
          name: styling-dist
          path: VDR/server-styling/dist
      - name: Retrieve glyphs
        uses: actions/download-artifact@v3
        with:
          name: glyphs
          path: VDR/server-styling/dist/glyphs
      - name: Run tileserver tests
        run: pytest VDR/chart-tiler/tests
